name: git action test

on:
  push:
    branches:
      - develop

jobs:
  workload-identity-connection:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: '**projects/175809265292/locations/global/workloadIdentityPools/github/providers/github-action**'
          service_account: 'deploy@hancomac.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
