name: CD

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Sign in to GCP
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/175809265292/locations/global/workloadIdentityPools/github/providers/github-action-api'
          service_account: 'deploy-api@hancomac.iam.gserviceaccount.com'

      - name: Use docker login action
        uses: 'docker/login-action@v1'
        with:
          registry: 'asia.gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Deploy image
        run: npm run deploy


