name: git action test

on:
  push:
    branches:
      - main

jobs:
  workload-identity-connection:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '**projects/175809265292/locations/global/workloadIdentityPools/github/providers/github-action**'
          service_account: 'deploy@hancomac.iam.gserviceaccount.com'
          audience: '//iam.googleapis.com/projects/175809265292/locations/global/workloadIdentityPools/github/providers/github-action'

      - name: use docker login action
        uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
